final List<Map<String, dynamic>> restaurantList = [
  {
    'title': 'Asparagus',
    'description': 'Delicious grilled asparagus.',
    'rating': 5.0,
    'tags': ['meals'],
    'imageUrl': 'https://i.pinimg.com/736x/6b/08/3b/6b083bd6cfa02b3ca4cce07a018600c8.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [
      {
        'name': 'VIP Room 1',
        'imageUrl': 'https://i.pinimg.com/736x/61/46/81/6146818ab5942e55707b075424c395a2.jpg',
        'description': 'Spacious and luxurious for private dining.',
      },
      {
        'name': 'VIP Room 2',
        'imageUrl': 'https://i.pinimg.com/736x/62/4d/5a/624d5a33250700c26855ec40ee44cf42.jpg',
        'description': 'Exclusive space with premium service.',
      },
    ],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Pizza Heaven',
    'description': 'The best pizza in town.',
    'rating': 4.5,
    'tags': ['meals', 'drinks'],
    'imageUrl': 'https://i.pinimg.com/736x/9d/7b/e2/9d7be2d2fda18436e04355c257f54996.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [
      {
        'name': 'VIP Room 1',
        'imageUrl': 'https://i.pinimg.com/736x/61/46/81/6146818ab5942e55707b075424c395a2.jpg',
        'description': 'A cozy VIP room with great pizza.',
      },
    ],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese daf adsafsdf fa safasfsa',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese daf adsafsdf fa safasfsa',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Sushi Palace',
    'description': 'Fresh and authentic sushi.',
    'rating': 4.8,
    'tags': ['meals'],
    'location':'damettia',
    'imageUrl': 'https://i.pinimg.com/736x/37/27/cb/3727cb35dc496a5bc37d0b28e0203606.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [
      {
        'name': 'VIP Room 1',
        'imageUrl': 'https://i.pinimg.com/736x/61/46/81/6146818ab5942e55707b075424c395a2.jpg',
        'description': 'Luxurious and quiet room for private dining.',
      },
    ],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Café Bliss',
    'description': 'Cozy cafe with artisanal coffee and pastries.',
    'rating': 4.7,
    'tags': ['drinks'],
    'location':'damettia',
    'imageUrl': 'https://i.pinimg.com/736x/00/6b/6b/006b6b4bfdc501d346df3e34bbc30e65.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Burger Town',
    'description': 'Juicy burgers and refreshing beverages.',
    'rating': 4.3,
    'tags': ['meals', 'drinks'],
    'imageUrl': 'https://i.pinimg.com/736x/5f/9d/f1/5f9df14cc46796cbb64af08e75b24d1e.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [
      {
        'name': 'VIP Room 1',
        'imageUrl': 'https://via.placeholder.com/150',
        'description': 'Perfect for private parties and gatherings.',
      },
    ],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Smoothie Corner',
    'description': 'Fresh and healthy smoothies with exotic fruits.',
    'rating': 4.6,
    'tags': ['drinks'],
    'imageUrl': 'https://i.pinimg.com/736x/e6/75/ca/e675ca3722051f26b924330841af0d4b.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  },
  {
    'title': 'Desserts Corner',
    'description': 'Fresh and healthy smoothies with exotic fruits.',
    'rating': 4.6,
    'tags': ['desserts'],
    'imageUrl': 'https://i.pinimg.com/736x/9e/34/28/9e342853906a986314b2687417f825f5.jpg',
    'galleryImages': [
      'https://via.placeholder.com/150',
      'https://via.placeholder.com/150',
    ],
    'layoutImage': 'https://i.pinimg.com/736x/3d/5b/a8/3d5ba8dbfc44cb0289960774e742c38e.jpg',
    'vipRooms': [],
    'tables': [
      {'id': 1, 'seats': 4, 'position': 'Window', 'isBooked': false},
      {'id': 2, 'seats': 2, 'position': 'Corner', 'isBooked': false},
      {'id': 3, 'seats': 6, 'position': 'Center', 'isBooked': false},
    ],
    'categories': [
      {
        'categoryName': 'Pasta',
        'meals': [
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
          {
            'mealName': 'Spaghetti Bolognese',
            'mealImage': 'https://i.pinimg.com/736x/14/ce/aa/14ceaa47a51211fbc4e2d8661dca66ec.jpg',
            'mealFavorites': true,
            'price': 15.99,
            'description': 'Classic Italian pasta with rich meat sauce.',
          },
        ],
      },
      {
        'categoryName': 'Salads',
        'meals': [
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
          {
            'mealName': 'Chicken Caesar Salad',
            'mealImage': 'https://i.pinimg.com/736x/72/d9/af/72d9af964d384fc2a16fd087c1062a7c.jpg',
            'mealFavorites': false,
            'price': 10.99,
            'description': 'Fresh Romaine lettuce with grilled chicken and Caesar dressing.',
          },
        ],
      },
    ],
  }
];
